import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

import { findMovie } from "../static/home";
import MovieCard from "../components/movieCard";

function Home({ genres }) {
  const [movies, setMovies] = useState([]);

  function handleSearch() {
    findMovie()
    .then((res) => setMovies(res));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Crazy App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <div className={styles.select}>
          <select name="Genres" id="genres_dropdown" defaultValue="">
            <option value="" disabled>
              Genre
            </option>
            {genres.map((genre, i) => (
              <option key={i} value={genre}>
                {i}: {genre}
              </option>
            ))}
          </select>
          <p>What will you watch today?</p>
          <button id="search" onClick={handleSearch}>
            Search
          </button>
        </div>

        <div id="movie-cards" className={styles.grid}>
          {movies.map((movie, i) => {
            return (
              <MovieCard movie={movie} key={i}/>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/genres");
  const genres = await res.json();

  console.log(genres);

  return {
    props: {
      genres,
    },
  };
}

export default Home;
