import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useState } from "react";

import { useGenre } from "../hooks/useGenre.js";

import MovieCards from "../components/MovieCards";
import GenrePicker from "../components/GenrePicker";



function Home({ genres }) {

  console.log(process.env.NODE_ENV);
  console.log(process.env.NEXT_PUBLIC_API_PATH);
  
  const [genre, handleGenre] = useGenre();
  const [movies, setMovies]  = useState([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Crazy App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        
        <GenrePicker chosenGenre={genre} genres={genres} handleGenre={handleGenre} setState={setMovies}/>
        
        <MovieCards movies={movies} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_PATH}/genres`);
  const genres = await res.json();

  console.log(genres);

  return {
    props: {
      genres,
    },
  };
}

export default Home;
